import Nav from '@/components/Nav'
import YieldProtocols from '@/components/YieldProtocols'
import LeaderboardSidebar from '@/components/LeaderboardSidebar'

export default function LeaderboardPage() {
  return (
    <div className="min-h-screen relative">
      <Nav />
      <main className="relative z-10 max-w-7xl mx-auto px-6 pt-12 pb-20">
        <div className="mb-8">
          <h1 className="text-3xl font-medium tracking-tight mb-2">Yield markets &amp; humans</h1>
          <p className="text-sm text-[var(--fg-muted)] max-w-2xl">
            Live APY for the Mantle DeFi protocols Mensa can allocate to. On the right,
            the humans who challenge the AI in the tournament.
          </p>
        </div>

        {/* Where the yield comes from */}
        <div className="card p-5 mb-6 max-w-3xl">
          <div className="text-[10px] uppercase tracking-wider text-[var(--accent)] mb-2">
            Where does the yield come from?
          </div>
          <p className="text-xs text-[var(--fg-muted)] leading-relaxed">
            Mensa allocates user deposits across these Mantle protocols. Yield is generated by:{' '}
            <span className="text-white">mETH liquid staking rewards</span>,{' '}
            <span className="text-white">Aave v3 lending markets</span>,{' '}
            <span className="text-white">Ondo USDY T-bill yield</span>, and{' '}
            <span className="text-white">Lendle pooled markets</span>.
            The AI agent decides the optimal split based on real-time APYs, risk tier, and ETH macro signals.
            15% of generated yield funds the bounty pool that rewards humans who beat the AI.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-[1fr_320px] gap-6">
          <YieldProtocols />
          <LeaderboardSidebar />
        </div>
      </main>
    </div>
  )
}
