import type { Metadata } from "next"
import { Inter, Geist_Mono } from "next/font/google"
import "./globals.css"
import { Providers } from "@/components/Providers"

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" })
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-mono" })

export const metadata: Metadata = {
  metadataBase: new URL("https://mensa-mu.vercel.app"),
  title: "Mensa — The AI treasury that proves itself",
  description: "Intelligent RWA portfolio management agent on Mantle. Allocates between mETH and USDY, with every decision logged on-chain and challenged by humans in a verifiable Turing tournament.",
  keywords: ["Mantle", "AI agent", "RWA", "mETH", "USDY", "Ondo", "DeFi", "Turing Test", "treasury"],
  // icon + apple-icon are generated by app/icon.tsx and app/apple-icon.png
  openGraph: {
    title: "Mensa — The AI treasury that proves itself",
    description: "Intelligent RWA portfolio management agent on Mantle. Every decision on-chain, every decision challenged.",
    url: "https://mensa-mu.vercel.app",
    siteName: "Mensa",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Mensa — The AI treasury that proves itself",
    description: "Intelligent RWA portfolio management agent on Mantle. AI vs humans, settled on-chain.",
  },
  // Virtual Protocol site verification. Renders as
  // <meta name="virtual-protocol-site-verification" content="..." />
  verification: {
    other: {
      "virtual-protocol-site-verification": "57803b18eb7f531853874d76ef5ce811",
    },
  },
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${inter.variable} ${geistMono.variable}`}>
      <body className="min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
